# LangChain Spring Boot应用配置
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: langchain-springboot
  profiles:
    active: dev

# LangChain4j配置
langchain4j:
  open-ai:
    chat-model:
      # 请在此处配置您的OpenAI API Key
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      model-name: gpt-3.5-turbo
      temperature: 0.7
      max-tokens: 1000
      timeout: 60s
    embedding-model:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      model-name: text-embedding-ada-002

# 日志配置
logging:
  level:
    com.example.langchain: DEBUG
    dev.langchain4j: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    restart:
      enabled: true

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.example.langchain: INFO
    dev.langchain4j: WARN