server:
  port: 8080
  servlet:
    context-path: /cpsc/privacy/testmock

spring:
  application:
    name: tool-service
  
  datasource:
    url: jdbc:mysql://localhost:3307/czp_java?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.tool.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      call-setters-on-nulls: true
      lazy-loading-enabled: false
      aggressive-lazy-loading: false
      # 添加调试信息
      log-prefix: "MyBatis: "
      # 注册拦截器
      plugins:
        - com.tool.config.SimpleSqlLogInterceptor
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.tool: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 