-- Mind map tables
CREATE TABLE IF NOT EXISTS mind_map (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  layout VARCHAR(50) NOT NULL DEFAULT 'mindmap',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS mind_map_node (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  map_id BIGINT NOT NULL,
  parent_id BIGINT NULL,
  text VARCHAR(1024) NOT NULL,
  x INT NOT NULL DEFAULT 0,
  y INT NOT NULL DEFAULT 0,
  width INT NOT NULL DEFAULT 100,
  height INT NOT NULL DEFAULT 50,
  shape VARCHAR(50) NOT NULL DEFAULT 'rectangle',
  background_color VARCHAR(20) NOT NULL DEFAULT '#2196F3',
  border_color VARCHAR(20) NOT NULL DEFAULT '#1976D2',
  font_size INT NOT NULL DEFAULT 14,
  is_root TINYINT(1) NOT NULL DEFAULT 0,
  collapsed TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT fk_mind_map_node_map FOREIGN KEY (map_id) REFERENCES mind_map(id) ON DELETE CASCADE,
  INDEX idx_map_id (map_id),
  INDEX idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 